#!C:\Users\admin\OneDrive - E 4 Energy Solutions\Saturn Pyro Files\Documents\Dell5Sync\NewVenv\Scripts\python.exe
try:
    from gevent import monkey; monkey.patch_all()  # noqa
except ImportError:
    import sys
    sys.stderr.write("error: gevent is missing. Run `pip install gevent`.")
    sys.exit(1)

import sys

from dramatiq.cli import main

if __name__ == "__main__":
    sys.exit(main())
